/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBase: typeof import('./components/AppBase.vue')['default']
    AppNavigation: typeof import('./components/AppNavigation.vue')['default']
    ContactInfo: typeof import('./components/ContactInfo.vue')['default']
    Heading: typeof import('./components/Heading.vue')['default']
    ResumeAbout: typeof import('./components/ResumeAbout.vue')['default']
    ResumeBase: typeof import('./components/ResumeBase.vue')['default']
    ResumeDownloadBtn: typeof import('./components/ResumeDownloadBtn.vue')['default']
    ResumeSection: typeof import('./components/ResumeSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillPill: typeof import('./components/SkillPill.vue')['default']
    SkillsList: typeof import('./components/SkillsList.vue')['default']
    Socials: typeof import('./components/Socials.vue')['default']
  }
}
